### ISSUE TITLE
懒加载 & WebP 无配置时报错

### ISSUE THREAD

**Issue by JesseJeson** [hifun-team/hexo-theme-miracle#24]
![image](https://user-images.githubusercontent.com/55904993/149695366-adad3572-3223-43e5-9a25-c3666aadc02c.png)

**Comment by JesseJeson** [comment]
还有文档里的json示例格式错了qwq

**Comment by ocoke** [comment]
请检查是否配置 [图片懒加载](https://www.notion.so/Miracle-49659de5b1764e908c7496418f06277e#82561a58ad6c4a6b942fdb1b9c47ca71)。

这确实是一个问题，后续将会增加判断防止报错。

**Comment by ocoke** [comment]
JSON 格式已修复。

**Comment by JesseJeson** [comment]
![image](https://user-images.githubusercontent.com/55904993/149869261-00eb17f0-25fc-49e7-a931-6ea0da5f5fbc.png)
配置了，还是报错
![image](https://user-images.githubusercontent.com/55904993/149869345-6a67e169-ebd0-473b-90a3-c353777d325c.png)

**Comment by ocoke** [comment]
请查阅文档。是在 `_config.yml` 中，而不是 `_config.miracle.yml` 中修改。

**Comment by JesseJeson** [comment]
哦哦，谢谢！
