### ISSUE TITLE
代码与行号不对齐的建议方案

### ISSUE THREAD

**Issue by pandaye** [hifun-team/hexo-theme-miracle#26]
#14 这个问题在 Linux 的 chrome 下 100% 复现，由于我自己用 Linux 所以很在意，我认为原因是出在这一段：
https://github.com/hifun-team/hexo-theme-miracle/blob/7791144be3795d93ce2a8e03eb2388cbf77b2312/source/css/_includes/post.styl#L251-L271
这里的 code 和 gutter 字体设置没有匹配，当 `font-size` 和 `line-height` 设置为一样的值，行号和代码就对齐了。不太明白为什么这里要写的不一样。

**Comment by ocoke** [comment]
到时候我测试下(

**Comment by ocoke** [comment]
问题已得到修复，将在稍候发布新版本。
