### ISSUE TITLE
不蒜子访客数统计页脚位置偏移

### ISSUE THREAD

**Issue by histcat** [hifun-team/hexo-theme-miracle#28]
![rt](https://user-images.githubusercontent.com/83163975/185748199-a633307f-9eac-47a5-833f-c98e5fdaf4d4.PNG)
如图

个人修改在页脚不蒜子显示外套一层`<p> </p>` 就好了qwq

**Comment by histcat** [comment]
呃呃呃
```html
<p> </p>
```

**Comment by ocoke** [comment]
问题已得到修复，将在稍候发布新版本。
